// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3946.DiagRobot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Relay spikeTestSpike1;
    public static Relay spikeTestSpike2;
    public static Relay spikeTestSpike3;
    public static Relay spikeTestSpike4;
    public static Relay spikeTestSpike5;
    public static Relay spikeTestSpike6;
    public static Relay spikeTestSpike7;
    public static Relay spikeTestSpike8;
    public static SpeedController pWMTestSpeedController1;
    public static SpeedController pWMTestSpeedController2;
    public static SpeedController pWMTestSpeedController3;
    public static SpeedController pWMTestSpeedController4;
    public static SpeedController pWMTestSpeedController5;
    public static SpeedController pWMTestSpeedController6;
    public static SpeedController pWMTestSpeedController7;
    public static SpeedController pWMTestSpeedController8;
    public static SpeedController pWMTestSpeedController9;
    public static SpeedController pWMTestSpeedController10;
    public static Solenoid solenoidTestSolenoid1;
    public static Solenoid solenoidTestSolenoid2;
    public static Solenoid solenoidTestSolenoid3;
    public static Solenoid solenoidTestSolenoid4;
    public static Solenoid solenoidTestSolenoid5;
    public static Solenoid solenoidTestSolenoid6;
    public static Solenoid solenoidTestSolenoid7;
    public static Solenoid solenoidTestSolenoid8;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        spikeTestSpike1 = new Relay(1, 1);
	LiveWindow.addActuator("SpikeTest", "Spike 1", spikeTestSpike1);
        
        spikeTestSpike2 = new Relay(1, 2);
	LiveWindow.addActuator("SpikeTest", "Spike 2", spikeTestSpike2);
        
        spikeTestSpike3 = new Relay(1, 3);
	LiveWindow.addActuator("SpikeTest", "Spike 3", spikeTestSpike3);
        
        spikeTestSpike4 = new Relay(1, 4);
	LiveWindow.addActuator("SpikeTest", "Spike 4", spikeTestSpike4);
        
        spikeTestSpike5 = new Relay(1, 5);
	LiveWindow.addActuator("SpikeTest", "Spike 5", spikeTestSpike5);
        
        spikeTestSpike6 = new Relay(1, 6);
	LiveWindow.addActuator("SpikeTest", "Spike 6", spikeTestSpike6);
        
        spikeTestSpike7 = new Relay(1, 7);
	LiveWindow.addActuator("SpikeTest", "Spike 7", spikeTestSpike7);
        
        spikeTestSpike8 = new Relay(1, 8);
	LiveWindow.addActuator("SpikeTest", "Spike 8", spikeTestSpike8);
        
        pWMTestSpeedController1 = new Jaguar(1, 1);
	LiveWindow.addActuator("PWMTest", "Speed Controller 1", (Jaguar) pWMTestSpeedController1);
        
        pWMTestSpeedController2 = new Jaguar(1, 2);
	LiveWindow.addActuator("PWMTest", "Speed Controller 2", (Jaguar) pWMTestSpeedController2);
        
        pWMTestSpeedController3 = new Jaguar(1, 3);
	LiveWindow.addActuator("PWMTest", "Speed Controller 3", (Jaguar) pWMTestSpeedController3);
        
        pWMTestSpeedController4 = new Jaguar(1, 4);
	LiveWindow.addActuator("PWMTest", "Speed Controller 4", (Jaguar) pWMTestSpeedController4);
        
        pWMTestSpeedController5 = new Jaguar(1, 5);
	LiveWindow.addActuator("PWMTest", "Speed Controller 5", (Jaguar) pWMTestSpeedController5);
        
        pWMTestSpeedController6 = new Jaguar(1, 6);
	LiveWindow.addActuator("PWMTest", "Speed Controller 6", (Jaguar) pWMTestSpeedController6);
        
        pWMTestSpeedController7 = new Jaguar(1, 7);
	LiveWindow.addActuator("PWMTest", "Speed Controller 7", (Jaguar) pWMTestSpeedController7);
        
        pWMTestSpeedController8 = new Jaguar(1, 8);
	LiveWindow.addActuator("PWMTest", "Speed Controller 8", (Jaguar) pWMTestSpeedController8);
        
        pWMTestSpeedController9 = new Jaguar(1, 9);
	LiveWindow.addActuator("PWMTest", "Speed Controller 9", (Jaguar) pWMTestSpeedController9);
        
        pWMTestSpeedController10 = new Jaguar(1, 10);
	LiveWindow.addActuator("PWMTest", "Speed Controller 10", (Jaguar) pWMTestSpeedController10);
        
        solenoidTestSolenoid1 = new Solenoid(1, 1);
	LiveWindow.addActuator("SolenoidTest", "Solenoid 1", solenoidTestSolenoid1);
        
        solenoidTestSolenoid2 = new Solenoid(1, 2);
	LiveWindow.addActuator("SolenoidTest", "Solenoid 2", solenoidTestSolenoid2);
        
        solenoidTestSolenoid3 = new Solenoid(1, 3);
	LiveWindow.addActuator("SolenoidTest", "Solenoid 3", solenoidTestSolenoid3);
        
        solenoidTestSolenoid4 = new Solenoid(1, 4);
	LiveWindow.addActuator("SolenoidTest", "Solenoid 4", solenoidTestSolenoid4);
        
        solenoidTestSolenoid5 = new Solenoid(1, 5);
	LiveWindow.addActuator("SolenoidTest", "Solenoid 5", solenoidTestSolenoid5);
        
        solenoidTestSolenoid6 = new Solenoid(1, 6);
	LiveWindow.addActuator("SolenoidTest", "Solenoid 6", solenoidTestSolenoid6);
        
        solenoidTestSolenoid7 = new Solenoid(1, 7);
	LiveWindow.addActuator("SolenoidTest", "Solenoid 7", solenoidTestSolenoid7);
        
        solenoidTestSolenoid8 = new Solenoid(1, 8);
	LiveWindow.addActuator("SolenoidTest", "Solenoid 8", solenoidTestSolenoid8);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
