// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3946.DiagRobot.subsystems;
import org.usfirst.frc3946.DiagRobot.RobotMap;
import org.usfirst.frc3946.DiagRobot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class SolenoidTest extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Solenoid solenoid1 = RobotMap.solenoidTestSolenoid1;
    Solenoid solenoid2 = RobotMap.solenoidTestSolenoid2;
    Solenoid solenoid3 = RobotMap.solenoidTestSolenoid3;
    Solenoid solenoid4 = RobotMap.solenoidTestSolenoid4;
    Solenoid solenoid5 = RobotMap.solenoidTestSolenoid5;
    Solenoid solenoid6 = RobotMap.solenoidTestSolenoid6;
    Solenoid solenoid7 = RobotMap.solenoidTestSolenoid7;
    Solenoid solenoid8 = RobotMap.solenoidTestSolenoid8;
    
    private int currentSolenoid = 0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void increment() {
        if(currentSolenoid <= 8) {
            currentSolenoid++;
        } else {
            currentSolenoid = 1;
        }
        switch(currentSolenoid) {
            case 1:
                solenoid8.set(false);
                solenoid1.set(true);
                break;
            case 2:
                solenoid1.set(false);
                solenoid2.set(true);
                break;
            case 3:
                solenoid2.set(false);
                solenoid3.set(true);
                break;
            case 4:
                solenoid3.set(false);
                solenoid4.set(true);
                break;
            case 5:
                solenoid4.set(false);
                solenoid5.set(true);
                break;
            case 6:
                solenoid5.set(false);
                solenoid6.set(true);
                break;
            case 7:
                solenoid6.set(false);
                solenoid7.set(true);
                break;
            case 8:
                solenoid7.set(false);
                solenoid8.set(true);
                break;
        }
    }
}
